### ISSUE TITLE
Server-Side Rendering (SSR)

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/refresh-web#1]
https://angular.io/guide/universal
https://angular.io/guide/hydration

This can be added without breaking client-side rendering (to bundle with refresh) and we can write a separate server to provide server-side rendering to instances that need SEO

**Comment by jvyden** [comment]
Made some progress in [the SSR branch](https://github.com/LittleBigRefresh/refresh-web/tree/ssr), so here's where we're at:

- Pages get mostly rendered correctly unless they depend on HTTP requests, which I believe is a problem stemming from https://github.com/angular/universal/issues/3142.
- `<fa-icon>`s appear larger until the JS can execute on the client, which can be pretty distracting. I imagine this is an upstream issue with [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome). I'll have to make an issue at some point or try to resolve this on my own.

**Comment by jvyden** [comment]
![image](https://github.com/LittleBigRefresh/refresh-web/assets/40577357/a17eb1d7-6f1c-4db0-abcd-96dfbf2275cd)

Here's how it looks right now:

**Comment by jvyden** [comment]
The bug was fixed in Angular 16.0.5, so the website is now kinda usable without JavaScript. 

Here you can see that the categories have loaded successfully. The icons are still definitely scuffed, though:
![image](https://github.com/LittleBigRefresh/refresh-web/assets/40577357/db59a161-4029-48cc-aec3-282e9fa753d0)

**Comment by jvyden** [comment]
![image](https://github.com/LittleBigRefresh/refresh-web/assets/40577357/c25ccf3d-865f-432b-9c4b-66f2932451e7)

Found the issue - icons are now fixed. Most things seem to be functional so I'm happy merging this now - save for some functionality issues regarding scoring and sign-in. I think having a basic readonly layout is enough for now - otherwise we'd be dealing with sending over unhashed passwords and such for non-js clients.

Next up is setting up instructions on how to host this on a web server.

**Comment by jvyden** [comment]
Will update this branch, re-test, and hopefully merge soon enough.

**Comment by jvyden** [comment]
Oops, adding masonry grids ended up breaking SSR:

```
Build at: 2023-09-16T05:44:36.081Z - Hash: 7a5f79e726a026cf - Time: 21328ms

Compiled successfully.
./node_modules/masonry-layout/masonry.js:33
}( window, function factory( Outlayer, getSize ) {
   ^


ReferenceError: window is not defined
    at Object.82760 (./node_modules/masonry-layout/masonry.js:33:4)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.47767 (./node_modules/htmlparser2/lib/esm/index.js:60:1)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.27822 (./src/app/pages/forgot-password/forgot-password.component.html:7:31)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.11838 (./src/app/api/types/user-roles.ts:5:38)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.50041 (./src/app/app.component.ts:56:4)
    at __webpack_require__ (./webpack/bootstrap:19:1)

Node.js v20.6.1
A server error has occurred.
node exited with 1 code.
```

I'll have to do some more digging to see if we can stub the Window APIs the masonry grid module uses to get it semi-working.

**Comment by jvyden** [comment]
Found a fork that of the base `masonry` package that fixes it, so I decided to use it. Now, the problem is that HTTP requests are broken. Again. :confounded:

**Comment by jvyden** [comment]
Nevermind, the renderer was trying to use IPv6, which Bunkum doesn't listen on.

**Comment by jvyden** [comment]
Non-JS is broken, but it's in a good enough state to be merged. YOLO
